### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by thezoggy** [deltablot/malle#10]
# Question / free support

do you have live demo?
(github built page of /demo?)

d/ling and checking out demo doesnt work due to cors policy.
tossing demo folder on website also didnt work, as it wants to wrongly load js from a dist folder which doesnt exists...

**Comment by NicolasCARPi** [comment]
Hello,

Yeah it's still on my todolist... You should be able to git clone the repo and run `npm run dev-server`, and then access the demo at http://localhost:4813/demo/

**Comment by NicolasCARPi** [comment]
Here it is: https://deltablot.github.io/malle/
