### ISSUE TITLE
Start editing with button

### ISSUE THREAD

**Issue by vitlia** [deltablot/malle#13]
# Feature request

I want to trigger editing using a button (icon). I created a custom event, configured Malle to listen for it, trigger it with my button. It works fine. But I hide the button when editing starts. I configured Malle to use OK/Cancel buttons. When user is done I want to show edit button again. I used "after" option to show icon when user clicks OK. But I did not find a hook for Cancel button. Malle does not provide any event. 
In the jeditable that I used before (it is referenced me to this project), the was event onReset, that fired when user cancels editing. Anything similar here?

**Comment by NicolasCARPi** [comment]
Hello,

No, `onReset` is not implemented, but I agree it should.

**Comment by NicolasCARPi** [comment]
See [onCancel](https://deltablot.github.io/malle/api/interfaces/Options.html#onCancel.onCancel-1) ;)

**Comment by vitlia** [comment]
Thank you for quick response. I will check it soon.
