### ISSUE TITLE
Single Edit, Save & Cancel Functionality

### ISSUE THREAD

**Issue by saidcc** [deltablot/malle#2]
# Is it possible to use a single edit, save and cancel button for an entire form instead of clicking each element and edit individually?

As it currently works Malle requires that a user click or mouseovers each element to be edited. Is it possible to change that behaviour so that there is initially a single edit button which when clicked makes all the elements editable/transforms to input. The elements are also saved using just the one saved button.

This is a very basic example but indicates the requirement

https://codepen.io/saidcc/pen/JjrZegb?editors=1111

Thanks

**Comment by NicolasCARPi** [comment]
Hello,

No this is not possible AFAIK, as the code is really "element-focused".
